COLUMN_MAPPING = {
    "product_master": {
        "product_code": "product_code",
        "barcode": "barcode",
        "style_code": "style_code",
        "style_name": "style_name",
        "product_name": "product_name",
        "brand": "brand",
        "division": "division",
        "department": "department",
        "category": "category",
        "sub_category": "sub_category",
        "season": "season",
        "collection": "collection",
        "color_code": "color_code",
        "color_name": "color_name",
        "size_code": "size_code",
        "size_name": "size_name",
        "gender": "gender",
        "age_group": "age_group",
        "lifecycle_status": "lifecycle_status",
        "launch_date": "launch_date",
        "discontinue_date": "discontinue_date",
        "unit_cost": "unit_cost",
        "retail_price": "retail_price",
        "vat_rate": "vat_rate",
        "is_active": "is_active",
    },

    "location_master": {
        "location_code": "location_code",
        "location_name": "location_name",
        "location_type": "location_type",
        "location_status": "location_status",
        "country": "country",
        "region": "region",
        "state": "state",
        "city": "city",
        "area": "area",
        "mall_name": "mall_name",
        "address": "address",
        "latitude": "latitude",
        "longitude": "longitude",
        "store_format": "store_format",
        "store_grade": "store_grade",
        "opening_date": "opening_date",
        "closing_date": "closing_date",
        "area_sqm": "area_sqm",
        "warehouse_capacity_units": "warehouse_capacity_units",
        "warehouse_capacity_cbm": "warehouse_capacity_cbm",
        "is_active": "is_active",
    },

    "supplier_master": {
        "supplier_code": "supplier_code",
        "supplier_name": "supplier_name",
        "supplier_type": "supplier_type",
        "supplier_category": "supplier_category",
        "supplier_country": "supplier_country",
        "supplier_region": "supplier_region",
        "supplier_state": "supplier_state",
        "supplier_city": "supplier_city",
        "supplier_address": "supplier_address",
        "contact_person": "contact_person",
        "contact_email": "contact_email",
        "contact_phone": "contact_phone",
        "payment_terms": "payment_terms",
        "default_currency": "default_currency",
        "standard_lead_time_days": "standard_lead_time_days",
        "minimum_order_qty": "minimum_order_qty",
        "supplier_status": "supplier_status",
        "is_active": "is_active",
    },

    "sales": {
        "sales_transaction_id": "sales_transaction_id",
        "sales_receipt_number": "sales_receipt_number",
        "sales_line_number": "sales_line_number",
        "product_code": "product_code",
        "location_code": "location_code",
        "transaction_date": "transaction_date",
        "transaction_time": "transaction_time",
        "promotion_code": "promotion_code",
        "channel_code": "channel_code",
        "sales_qty": "sales_qty",
        "gross_sales_amount": "gross_sales_amount",
        "discount_amount": "discount_amount",
        "net_sales_amount": "net_sales_amount",
        "vat_amount": "vat_amount",
        "unit_cost": "unit_cost",
        "cost_amount": "cost_amount",
        "unit_retail_price": "unit_retail_price",
        "gross_margin_amount": "gross_margin_amount",
    },

    "inventory_snapshot": {
        "snapshot_date": "snapshot_date",
        "product_code": "product_code",
        "location_code": "location_code",
        "stock_on_hand_qty": "stock_on_hand_qty",
        "available_qty": "available_qty",
        "reserved_qty": "reserved_qty",
        "in_transit_qty": "in_transit_qty",
        "on_order_qty": "on_order_qty",
        "unit_cost": "unit_cost",
        "unit_retail_price": "unit_retail_price",
        "inventory_cost_value": "inventory_cost_value",
        "inventory_retail_value": "inventory_retail_value",
        "stock_cover_days": "stock_cover_days",
    },

    "inventory_movement": {
        "movement_document_number": "movement_document_number",
        "movement_document_line_number": "movement_document_line_number",
        "source_document_number": "source_document_number",
        "source_document_line_number": "source_document_line_number",
        "product_code": "product_code",
        "location_code": "location_code",
        "movement_date": "movement_date",
        "movement_type_code": "movement_type_code",
        "movement_qty": "movement_qty",
        "unit_cost": "unit_cost",
        "unit_retail_price": "unit_retail_price",
        "movement_cost_value": "movement_cost_value",
        "movement_retail_value": "movement_retail_value",
    },

    "purchase_orders": {
        "po_number": "po_number",
        "po_line_number": "po_line_number",
        "supplier_reference_number": "supplier_reference_number",
        "product_code": "product_code",
        "supplier_code": "supplier_code",
        "receiving_location_code": "receiving_location_code",
        "order_date": "order_date",
        "expected_delivery_date": "expected_delivery_date",
        "po_status_code": "po_status_code",
        "ordered_qty": "ordered_qty",
        "cancelled_qty": "cancelled_qty",
        "open_qty": "open_qty",
        "remaining_qty": "remaining_qty",
        "carton_qty": "carton_qty",
        "unit_cost": "unit_cost",
        "ordered_cost_value": "ordered_cost_value",
    },

    "goods_receipts": {
        "grn_number": "grn_number",
        "grn_line_number": "grn_line_number",
        "po_number": "po_number",
        "po_line_number": "po_line_number",
        "product_code": "product_code",
        "supplier_code": "supplier_code",
        "receiving_location_code": "receiving_location_code",
        "receipt_date": "receipt_date",
        "expected_delivery_date": "expected_delivery_date",
        "receipt_status_code": "receipt_status_code",
        "received_qty": "received_qty",
        "accepted_qty": "accepted_qty",
        "rejected_qty": "rejected_qty",
        "short_qty": "short_qty",
        "excess_qty": "excess_qty",
        "defect_qty": "defect_qty",
        "carton_qty": "carton_qty",
        "unit_cost": "unit_cost",
        "received_cost_value": "received_cost_value",
    },

    "transfers": {
        "transfer_order_number": "transfer_order_number",
        "transfer_line_number": "transfer_line_number",
        "shipment_number": "shipment_number",
        "delivery_note_number": "delivery_note_number",
        "product_code": "product_code",
        "from_location_code": "from_location_code",
        "to_location_code": "to_location_code",
        "transfer_created_date": "transfer_created_date",
        "shipped_date": "shipped_date",
        "received_date": "received_date",
        "expected_receipt_date": "expected_receipt_date",
        "transfer_status_code": "transfer_status_code",
        "requested_transfer_qty": "requested_transfer_qty",
        "shipped_qty": "shipped_qty",
        "received_qty": "received_qty",
        "short_qty": "short_qty",
        "excess_qty": "excess_qty",
        "in_transit_qty": "in_transit_qty",
        "carton_qty": "carton_qty",
        "unit_cost": "unit_cost",
        "unit_retail_price": "unit_retail_price",
        "transfer_cost_value": "transfer_cost_value",
        "transfer_retail_value": "transfer_retail_value",
    },

    "forecast": {
        "product_code": "product_code",
        "location_code": "location_code",
        "forecast_period_date": "forecast_period_date",
        "forecast_run_date": "forecast_run_date",
        "channel_code": "channel_code",
        "promotion_code": "promotion_code",
        "forecast_model_code": "forecast_model_code",
        "forecast_version": "forecast_version",
        "forecast_batch_id": "forecast_batch_id",
        "forecast_qty": "forecast_qty",
        "actual_qty": "actual_qty",
        "forecast_error_qty": "forecast_error_qty",
        "absolute_error_qty": "absolute_error_qty",
        "squared_error_qty": "squared_error_qty",
        "mape_percentage": "mape_percentage",
        "bias_percentage": "bias_percentage",
        "forecast_accuracy_percentage": "forecast_accuracy_percentage",
    },

    "stock_optimization": {
        "product_code": "product_code",
        "location_code": "location_code",
        "optimization_run_date": "optimization_run_date",
        "optimization_model_code": "optimization_model_code",
        "avg_daily_sales": "avg_daily_sales",
        "demand_std_dev": "demand_std_dev",
        "lead_time_days": "lead_time_days",
        "service_level": "service_level",
        "safety_stock_qty": "safety_stock_qty",
        "reorder_point_qty": "reorder_point_qty",
        "recommended_order_qty": "recommended_order_qty",
        "stock_cover_days": "stock_cover_days",
        "abc_class": "abc_class",
        "xyz_class": "xyz_class",
        "fsn_class": "fsn_class",
        "inventory_health_score": "inventory_health_score",
        "recommendation": "recommendation",
    },
}


def get_column_mapping(file_type: str) -> dict:
    """
    Return source-to-target column mapping for one file type.
    """

    if file_type not in COLUMN_MAPPING:
        raise ValueError(f"Unknown file type: {file_type}")

    return COLUMN_MAPPING[file_type]