import pandas as pd

from config.file_config import get_file_config


SAMPLE_DATA = {
    "product_master": [
        {
            "product_code": "JC-SH-001-S-BLU",
            "barcode": "629100000001",
            "style_code": "JC-SH-001",
            "style_name": "Classic Shirt",
            "product_name": "Classic Blue Shirt Small",
            "brand": "Jacadi",
            "division": "Kidswear",
            "department": "Boys",
            "category": "Shirts",
            "sub_category": "Casual Shirts",
            "season": "26S",
            "collection": "Spring Summer",
            "color_code": "BLU",
            "color_name": "Blue",
            "size_code": "S",
            "size_name": "Small",
            "gender": "Boys",
            "age_group": "Kids",
            "lifecycle_status": "Seasonal",
            "launch_date": "2026-03-01",
            "discontinue_date": None,
            "unit_cost": 42.00,
            "retail_price": 129.00,
            "vat_rate": 5.00,
            "is_active": 1,
        },
        {
            "product_code": "JC-SH-001-M-BLU",
            "barcode": "629100000002",
            "style_code": "JC-SH-001",
            "style_name": "Classic Shirt",
            "product_name": "Classic Blue Shirt Medium",
            "brand": "Jacadi",
            "division": "Kidswear",
            "department": "Boys",
            "category": "Shirts",
            "sub_category": "Casual Shirts",
            "season": "26S",
            "collection": "Spring Summer",
            "color_code": "BLU",
            "color_name": "Blue",
            "size_code": "M",
            "size_name": "Medium",
            "gender": "Boys",
            "age_group": "Kids",
            "lifecycle_status": "Seasonal",
            "launch_date": "2026-03-01",
            "discontinue_date": None,
            "unit_cost": 42.00,
            "retail_price": 129.00,
            "vat_rate": 5.00,
            "is_active": 1,
        },
        {
            "product_code": "OK-DR-010-4-PNK",
            "barcode": "629100000003",
            "style_code": "OK-DR-010",
            "style_name": "Summer Dress",
            "product_name": "Pink Summer Dress Age 4",
            "brand": "Okaidi",
            "division": "Kidswear",
            "department": "Girls",
            "category": "Dresses",
            "sub_category": "Casual Dresses",
            "season": "26S",
            "collection": "Spring Summer",
            "color_code": "PNK",
            "color_name": "Pink",
            "size_code": "4Y",
            "size_name": "4 Years",
            "gender": "Girls",
            "age_group": "Kids",
            "lifecycle_status": "Seasonal",
            "launch_date": "2026-03-15",
            "discontinue_date": None,
            "unit_cost": 55.00,
            "retail_price": 169.00,
            "vat_rate": 5.00,
            "is_active": 1,
        },
        {
            "product_code": "UZ-TS-050-M-BLK",
            "barcode": "629100000004",
            "style_code": "UZ-TS-050",
            "style_name": "Basic T-Shirt",
            "product_name": "Black Basic T-Shirt Medium",
            "brand": "Undiz",
            "division": "Apparel",
            "department": "Women",
            "category": "T-Shirts",
            "sub_category": "Basic T-Shirts",
            "season": "CORE",
            "collection": "Core",
            "color_code": "BLK",
            "color_name": "Black",
            "size_code": "M",
            "size_name": "Medium",
            "gender": "Women",
            "age_group": "Adult",
            "lifecycle_status": "Core",
            "launch_date": "2025-01-01",
            "discontinue_date": None,
            "unit_cost": 18.00,
            "retail_price": 59.00,
            "vat_rate": 5.00,
            "is_active": 1,
        },
        {
            "product_code": "PA-BG-020-STD-BGE",
            "barcode": "629100000005",
            "style_code": "PA-BG-020",
            "style_name": "Everyday Bag",
            "product_name": "Beige Everyday Bag",
            "brand": "Parfois",
            "division": "Accessories",
            "department": "Women",
            "category": "Bags",
            "sub_category": "Shoulder Bags",
            "season": "26S",
            "collection": "Spring Summer",
            "color_code": "BGE",
            "color_name": "Beige",
            "size_code": "STD",
            "size_name": "Standard",
            "gender": "Women",
            "age_group": "Adult",
            "lifecycle_status": "New",
            "launch_date": "2026-04-01",
            "discontinue_date": None,
            "unit_cost": 65.00,
            "retail_price": 199.00,
            "vat_rate": 5.00,
            "is_active": 1,
        },
    ],

    "location_master": [
        {
            "location_code": "DXB001",
            "location_name": "Dubai Mall Store",
            "location_type": "Store",
            "location_status": "Active",
            "country": "UAE",
            "region": "Dubai",
            "state": "Dubai",
            "city": "Dubai",
            "area": "Downtown",
            "mall_name": "Dubai Mall",
            "address": "Downtown Dubai",
            "latitude": 25.1972,
            "longitude": 55.2744,
            "store_format": "Flagship",
            "store_grade": "A",
            "opening_date": "2020-01-01",
            "closing_date": None,
            "area_sqm": 450.00,
            "warehouse_capacity_units": None,
            "warehouse_capacity_cbm": None,
            "is_active": 1,
        },
        {
            "location_code": "SHJ001",
            "location_name": "City Centre Sharjah Store",
            "location_type": "Store",
            "location_status": "Active",
            "country": "UAE",
            "region": "Sharjah",
            "state": "Sharjah",
            "city": "Sharjah",
            "area": "Al Wahda",
            "mall_name": "City Centre Sharjah",
            "address": "Sharjah",
            "latitude": 25.3463,
            "longitude": 55.4209,
            "store_format": "Mall Store",
            "store_grade": "B",
            "opening_date": "2021-06-01",
            "closing_date": None,
            "area_sqm": 280.00,
            "warehouse_capacity_units": None,
            "warehouse_capacity_cbm": None,
            "is_active": 1,
        },
        {
            "location_code": "AUH001",
            "location_name": "Yas Mall Store",
            "location_type": "Store",
            "location_status": "Active",
            "country": "UAE",
            "region": "Abu Dhabi",
            "state": "Abu Dhabi",
            "city": "Abu Dhabi",
            "area": "Yas Island",
            "mall_name": "Yas Mall",
            "address": "Yas Island",
            "latitude": 24.4889,
            "longitude": 54.6074,
            "store_format": "Mall Store",
            "store_grade": "A",
            "opening_date": "2022-03-01",
            "closing_date": None,
            "area_sqm": 320.00,
            "warehouse_capacity_units": None,
            "warehouse_capacity_cbm": None,
            "is_active": 1,
        },
        {
            "location_code": "WH001",
            "location_name": "Dubai Central Warehouse",
            "location_type": "Warehouse",
            "location_status": "Active",
            "country": "UAE",
            "region": "Dubai",
            "state": "Dubai",
            "city": "Dubai",
            "area": "Jebel Ali",
            "mall_name": None,
            "address": "Jebel Ali Free Zone",
            "latitude": 24.9857,
            "longitude": 55.09,
            "store_format": "Warehouse",
            "store_grade": "A",
            "opening_date": "2019-01-01",
            "closing_date": None,
            "area_sqm": 2500.00,
            "warehouse_capacity_units": 250000,
            "warehouse_capacity_cbm": 15000.00,
            "is_active": 1,
        },
    ],

    "supplier_master": [
        {
            "supplier_code": "SUP-FR-001",
            "supplier_name": "Paris Apparel Manufacturing",
            "supplier_type": "International",
            "supplier_category": "Finished Goods Supplier",
            "supplier_country": "France",
            "supplier_region": "Europe",
            "supplier_state": "Ile-de-France",
            "supplier_city": "Paris",
            "supplier_address": "Paris Industrial Zone",
            "contact_person": "Marie Laurent",
            "contact_email": "marie@supplier.com",
            "contact_phone": "+33100000001",
            "payment_terms": "Net 45",
            "default_currency": "EUR",
            "standard_lead_time_days": 21,
            "minimum_order_qty": 100,
            "supplier_status": "Active",
            "is_active": 1,
        },
        {
            "supplier_code": "SUP-TR-002",
            "supplier_name": "Istanbul Textile Group",
            "supplier_type": "International",
            "supplier_category": "Finished Goods Supplier",
            "supplier_country": "Turkey",
            "supplier_region": "EMEA",
            "supplier_state": "Istanbul",
            "supplier_city": "Istanbul",
            "supplier_address": "Textile District",
            "contact_person": "Ahmet Yilmaz",
            "contact_email": "ahmet@supplier.com",
            "contact_phone": "+902120000002",
            "payment_terms": "Net 30",
            "default_currency": "USD",
            "standard_lead_time_days": 18,
            "minimum_order_qty": 150,
            "supplier_status": "Active",
            "is_active": 1,
        },
        {
            "supplier_code": "SUP-CN-003",
            "supplier_name": "Shenzhen Accessories Ltd",
            "supplier_type": "International",
            "supplier_category": "Accessories Supplier",
            "supplier_country": "China",
            "supplier_region": "Asia",
            "supplier_state": "Guangdong",
            "supplier_city": "Shenzhen",
            "supplier_address": "Shenzhen Export Zone",
            "contact_person": "Li Wei",
            "contact_email": "liwei@supplier.com",
            "contact_phone": "+8613000000003",
            "payment_terms": "Net 60",
            "default_currency": "USD",
            "standard_lead_time_days": 35,
            "minimum_order_qty": 200,
            "supplier_status": "Active",
            "is_active": 1,
        },
    ],

    "sales": [
        {
            "sales_transaction_id": "TXN-10001",
            "sales_receipt_number": "RCPT-10001",
            "sales_line_number": 1,
            "product_code": "JC-SH-001-S-BLU",
            "location_code": "DXB001",
            "transaction_date": "2026-07-01",
            "transaction_time": "10:15:00",
            "promotion_code": "SUMMER25",
            "channel_code": "RETAIL",
            "sales_qty": 2,
            "gross_sales_amount": 258.00,
            "discount_amount": 64.50,
            "net_sales_amount": 193.50,
            "vat_amount": 9.68,
            "unit_cost": 42.00,
            "cost_amount": 84.00,
            "unit_retail_price": 129.00,
            "gross_margin_amount": 109.50,
        },
        {
            "sales_transaction_id": "TXN-10001",
            "sales_receipt_number": "RCPT-10001",
            "sales_line_number": 2,
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "DXB001",
            "transaction_date": "2026-07-01",
            "transaction_time": "10:15:00",
            "promotion_code": None,
            "channel_code": "RETAIL",
            "sales_qty": 1,
            "gross_sales_amount": 199.00,
            "discount_amount": 0.00,
            "net_sales_amount": 199.00,
            "vat_amount": 9.95,
            "unit_cost": 65.00,
            "cost_amount": 65.00,
            "unit_retail_price": 199.00,
            "gross_margin_amount": 134.00,
        },
        {
            "sales_transaction_id": "TXN-10002",
            "sales_receipt_number": "RCPT-10002",
            "sales_line_number": 1,
            "product_code": "OK-DR-010-4-PNK",
            "location_code": "SHJ001",
            "transaction_date": "2026-07-02",
            "transaction_time": "14:30:00",
            "promotion_code": "SUMMER25",
            "channel_code": "RETAIL",
            "sales_qty": 1,
            "gross_sales_amount": 169.00,
            "discount_amount": 42.25,
            "net_sales_amount": 126.75,
            "vat_amount": 6.34,
            "unit_cost": 55.00,
            "cost_amount": 55.00,
            "unit_retail_price": 169.00,
            "gross_margin_amount": 71.75,
        },
        {
            "sales_transaction_id": "TXN-10003",
            "sales_receipt_number": "RCPT-10003",
            "sales_line_number": 1,
            "product_code": "UZ-TS-050-M-BLK",
            "location_code": "AUH001",
            "transaction_date": "2026-07-02",
            "transaction_time": "18:45:00",
            "promotion_code": None,
            "channel_code": "RETAIL",
            "sales_qty": 3,
            "gross_sales_amount": 177.00,
            "discount_amount": 0.00,
            "net_sales_amount": 177.00,
            "vat_amount": 8.85,
            "unit_cost": 18.00,
            "cost_amount": 54.00,
            "unit_retail_price": 59.00,
            "gross_margin_amount": 123.00,
        },
        {
            "sales_transaction_id": "TXN-10004",
            "sales_receipt_number": "RCPT-10004",
            "sales_line_number": 1,
            "product_code": "JC-SH-001-M-BLU",
            "location_code": "DXB001",
            "transaction_date": "2026-07-03",
            "transaction_time": "12:05:00",
            "promotion_code": "SUMMER25",
            "channel_code": "RETAIL",
            "sales_qty": 1,
            "gross_sales_amount": 129.00,
            "discount_amount": 32.25,
            "net_sales_amount": 96.75,
            "vat_amount": 4.84,
            "unit_cost": 42.00,
            "cost_amount": 42.00,
            "unit_retail_price": 129.00,
            "gross_margin_amount": 54.75,
        },
        {
            "sales_transaction_id": "TXN-10005",
            "sales_receipt_number": "RCPT-10005",
            "sales_line_number": 1,
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "AUH001",
            "transaction_date": "2026-07-04",
            "transaction_time": "16:20:00",
            "promotion_code": None,
            "channel_code": "RETAIL",
            "sales_qty": 2,
            "gross_sales_amount": 398.00,
            "discount_amount": 0.00,
            "net_sales_amount": 398.00,
            "vat_amount": 19.90,
            "unit_cost": 65.00,
            "cost_amount": 130.00,
            "unit_retail_price": 199.00,
            "gross_margin_amount": 268.00,
        },
    ],

    "inventory_snapshot": [
        {
            "snapshot_date": "2026-07-04",
            "product_code": "JC-SH-001-S-BLU",
            "location_code": "DXB001",
            "stock_on_hand_qty": 18,
            "available_qty": 18,
            "reserved_qty": 0,
            "in_transit_qty": 0,
            "on_order_qty": 40,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "inventory_cost_value": 756.00,
            "inventory_retail_value": 2322.00,
            "stock_cover_days": 18,
        },
        {
            "snapshot_date": "2026-07-04",
            "product_code": "JC-SH-001-M-BLU",
            "location_code": "DXB001",
            "stock_on_hand_qty": 5,
            "available_qty": 5,
            "reserved_qty": 0,
            "in_transit_qty": 10,
            "on_order_qty": 30,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "inventory_cost_value": 210.00,
            "inventory_retail_value": 645.00,
            "stock_cover_days": 5,
        },
        {
            "snapshot_date": "2026-07-04",
            "product_code": "OK-DR-010-4-PNK",
            "location_code": "SHJ001",
            "stock_on_hand_qty": 30,
            "available_qty": 30,
            "reserved_qty": 0,
            "in_transit_qty": 0,
            "on_order_qty": 20,
            "unit_cost": 55.00,
            "unit_retail_price": 169.00,
            "inventory_cost_value": 1650.00,
            "inventory_retail_value": 5070.00,
            "stock_cover_days": 45,
        },
        {
            "snapshot_date": "2026-07-04",
            "product_code": "UZ-TS-050-M-BLK",
            "location_code": "AUH001",
            "stock_on_hand_qty": 12,
            "available_qty": 12,
            "reserved_qty": 0,
            "in_transit_qty": 0,
            "on_order_qty": 0,
            "unit_cost": 18.00,
            "unit_retail_price": 59.00,
            "inventory_cost_value": 216.00,
            "inventory_retail_value": 708.00,
            "stock_cover_days": 8,
        },
        {
            "snapshot_date": "2026-07-04",
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "DXB001",
            "stock_on_hand_qty": 4,
            "available_qty": 4,
            "reserved_qty": 0,
            "in_transit_qty": 0,
            "on_order_qty": 25,
            "unit_cost": 65.00,
            "unit_retail_price": 199.00,
            "inventory_cost_value": 260.00,
            "inventory_retail_value": 796.00,
            "stock_cover_days": 4,
        },
        {
            "snapshot_date": "2026-07-04",
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "AUH001",
            "stock_on_hand_qty": 9,
            "available_qty": 9,
            "reserved_qty": 0,
            "in_transit_qty": 0,
            "on_order_qty": 25,
            "unit_cost": 65.00,
            "unit_retail_price": 199.00,
            "inventory_cost_value": 585.00,
            "inventory_retail_value": 1791.00,
            "stock_cover_days": 12,
        },
    ],

    "inventory_movement": [
        {
            "movement_document_number": "MOV-10001",
            "movement_document_line_number": 1,
            "source_document_number": "RCPT-10001",
            "source_document_line_number": 1,
            "product_code": "JC-SH-001-S-BLU",
            "location_code": "DXB001",
            "movement_date": "2026-07-01",
            "movement_type_code": "SALE",
            "movement_qty": -2,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "movement_cost_value": -84.00,
            "movement_retail_value": -258.00,
        },
        {
            "movement_document_number": "MOV-10002",
            "movement_document_line_number": 1,
            "source_document_number": "GRN-90001",
            "source_document_line_number": 1,
            "product_code": "JC-SH-001-S-BLU",
            "location_code": "WH001",
            "movement_date": "2026-07-01",
            "movement_type_code": "PURCHASE_RECEIPT",
            "movement_qty": 50,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "movement_cost_value": 2100.00,
            "movement_retail_value": 6450.00,
        },
        {
            "movement_document_number": "MOV-10003",
            "movement_document_line_number": 1,
            "source_document_number": "TO-70001",
            "source_document_line_number": 1,
            "product_code": "JC-SH-001-M-BLU",
            "location_code": "WH001",
            "movement_date": "2026-07-02",
            "movement_type_code": "TRANSFER_OUT",
            "movement_qty": -10,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "movement_cost_value": -420.00,
            "movement_retail_value": -1290.00,
        },
        {
            "movement_document_number": "MOV-10004",
            "movement_document_line_number": 1,
            "source_document_number": "TO-70001",
            "source_document_line_number": 1,
            "product_code": "JC-SH-001-M-BLU",
            "location_code": "DXB001",
            "movement_date": "2026-07-03",
            "movement_type_code": "TRANSFER_IN",
            "movement_qty": 8,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "movement_cost_value": 336.00,
            "movement_retail_value": 1032.00,
        },
        {
            "movement_document_number": "MOV-10005",
            "movement_document_line_number": 1,
            "source_document_number": "ADJ-50001",
            "source_document_line_number": 1,
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "DXB001",
            "movement_date": "2026-07-04",
            "movement_type_code": "SHRINKAGE",
            "movement_qty": -1,
            "unit_cost": 65.00,
            "unit_retail_price": 199.00,
            "movement_cost_value": -65.00,
            "movement_retail_value": -199.00,
        },
    ],

    "purchase_orders": [
        {
            "po_number": "PO-80001",
            "po_line_number": 1,
            "supplier_reference_number": "SUPREF-001",
            "product_code": "JC-SH-001-S-BLU",
            "supplier_code": "SUP-FR-001",
            "receiving_location_code": "WH001",
            "order_date": "2026-06-10",
            "expected_delivery_date": "2026-07-01",
            "po_status_code": "FULLY_RECEIVED",
            "ordered_qty": 50,
            "cancelled_qty": 0,
            "open_qty": 0,
            "remaining_qty": 0,
            "carton_qty": 5,
            "unit_cost": 42.00,
            "ordered_cost_value": 2100.00,
        },
        {
            "po_number": "PO-80002",
            "po_line_number": 1,
            "supplier_reference_number": "SUPREF-002",
            "product_code": "OK-DR-010-4-PNK",
            "supplier_code": "SUP-TR-002",
            "receiving_location_code": "WH001",
            "order_date": "2026-06-20",
            "expected_delivery_date": "2026-07-08",
            "po_status_code": "OPEN",
            "ordered_qty": 40,
            "cancelled_qty": 0,
            "open_qty": 40,
            "remaining_qty": 40,
            "carton_qty": 4,
            "unit_cost": 55.00,
            "ordered_cost_value": 2200.00,
        },
        {
            "po_number": "PO-80003",
            "po_line_number": 1,
            "supplier_reference_number": "SUPREF-003",
            "product_code": "PA-BG-020-STD-BGE",
            "supplier_code": "SUP-CN-003",
            "receiving_location_code": "WH001",
            "order_date": "2026-06-01",
            "expected_delivery_date": "2026-07-06",
            "po_status_code": "PARTIALLY_RECEIVED",
            "ordered_qty": 60,
            "cancelled_qty": 0,
            "open_qty": 25,
            "remaining_qty": 25,
            "carton_qty": 6,
            "unit_cost": 65.00,
            "ordered_cost_value": 3900.00,
        },
    ],

    "goods_receipts": [
        {
            "grn_number": "GRN-90001",
            "grn_line_number": 1,
            "po_number": "PO-80001",
            "po_line_number": 1,
            "product_code": "JC-SH-001-S-BLU",
            "supplier_code": "SUP-FR-001",
            "receiving_location_code": "WH001",
            "receipt_date": "2026-07-01",
            "expected_delivery_date": "2026-07-01",
            "receipt_status_code": "FULLY_RECEIVED",
            "received_qty": 50,
            "accepted_qty": 50,
            "rejected_qty": 0,
            "short_qty": 0,
            "excess_qty": 0,
            "defect_qty": 0,
            "carton_qty": 5,
            "unit_cost": 42.00,
            "received_cost_value": 2100.00,
        },
        {
            "grn_number": "GRN-90002",
            "grn_line_number": 1,
            "po_number": "PO-80003",
            "po_line_number": 1,
            "product_code": "PA-BG-020-STD-BGE",
            "supplier_code": "SUP-CN-003",
            "receiving_location_code": "WH001",
            "receipt_date": "2026-07-08",
            "expected_delivery_date": "2026-07-06",
            "receipt_status_code": "PARTIALLY_RECEIVED",
            "received_qty": 35,
            "accepted_qty": 34,
            "rejected_qty": 1,
            "short_qty": 25,
            "excess_qty": 0,
            "defect_qty": 1,
            "carton_qty": 4,
            "unit_cost": 65.00,
            "received_cost_value": 2275.00,
        },
    ],

    "transfers": [
        {
            "transfer_order_number": "TO-70001",
            "transfer_line_number": 1,
            "shipment_number": "SHIP-30001",
            "delivery_note_number": "DN-60001",
            "product_code": "JC-SH-001-M-BLU",
            "from_location_code": "WH001",
            "to_location_code": "DXB001",
            "transfer_created_date": "2026-07-02",
            "shipped_date": "2026-07-02",
            "received_date": "2026-07-03",
            "expected_receipt_date": "2026-07-03",
            "transfer_status_code": "RECEIVED",
            "requested_transfer_qty": 10,
            "shipped_qty": 10,
            "received_qty": 8,
            "short_qty": 2,
            "excess_qty": 0,
            "in_transit_qty": 0,
            "carton_qty": 1,
            "unit_cost": 42.00,
            "unit_retail_price": 129.00,
            "transfer_cost_value": 420.00,
            "transfer_retail_value": 1290.00,
        },
        {
            "transfer_order_number": "TO-70002",
            "transfer_line_number": 1,
            "shipment_number": "SHIP-30002",
            "delivery_note_number": "DN-60002",
            "product_code": "PA-BG-020-STD-BGE",
            "from_location_code": "WH001",
            "to_location_code": "DXB001",
            "transfer_created_date": "2026-07-04",
            "shipped_date": "2026-07-04",
            "received_date": None,
            "expected_receipt_date": "2026-07-05",
            "transfer_status_code": "IN_TRANSIT",
            "requested_transfer_qty": 15,
            "shipped_qty": 15,
            "received_qty": 0,
            "short_qty": 0,
            "excess_qty": 0,
            "in_transit_qty": 15,
            "carton_qty": 2,
            "unit_cost": 65.00,
            "unit_retail_price": 199.00,
            "transfer_cost_value": 975.00,
            "transfer_retail_value": 2985.00,
        },
    ],

    "forecast": [
        {
            "product_code": "JC-SH-001-S-BLU",
            "location_code": "DXB001",
            "forecast_period_date": "2026-07-07",
            "forecast_run_date": "2026-07-01",
            "channel_code": "RETAIL",
            "promotion_code": "SUMMER25",
            "forecast_model_code": "SARIMAX",
            "forecast_version": "V1",
            "forecast_batch_id": "FCST-20260701",
            "forecast_qty": 15,
            "actual_qty": 14,
            "forecast_error_qty": -1,
            "absolute_error_qty": 1,
            "squared_error_qty": 1,
            "mape_percentage": 0.0714,
            "bias_percentage": -0.0714,
            "forecast_accuracy_percentage": 0.9286,
        },
        {
            "product_code": "OK-DR-010-4-PNK",
            "location_code": "SHJ001",
            "forecast_period_date": "2026-07-07",
            "forecast_run_date": "2026-07-01",
            "channel_code": "RETAIL",
            "promotion_code": "SUMMER25",
            "forecast_model_code": "XGBOOST",
            "forecast_version": "V1",
            "forecast_batch_id": "FCST-20260701",
            "forecast_qty": 10,
            "actual_qty": 7,
            "forecast_error_qty": -3,
            "absolute_error_qty": 3,
            "squared_error_qty": 9,
            "mape_percentage": 0.4286,
            "bias_percentage": -0.4286,
            "forecast_accuracy_percentage": 0.5714,
        },
        {
            "product_code": "UZ-TS-050-M-BLK",
            "location_code": "AUH001",
            "forecast_period_date": "2026-07-07",
            "forecast_run_date": "2026-07-01",
            "channel_code": "RETAIL",
            "promotion_code": None,
            "forecast_model_code": "MOVING_AVG",
            "forecast_version": "V1",
            "forecast_batch_id": "FCST-20260701",
            "forecast_qty": 20,
            "actual_qty": 22,
            "forecast_error_qty": 2,
            "absolute_error_qty": 2,
            "squared_error_qty": 4,
            "mape_percentage": 0.0909,
            "bias_percentage": 0.0909,
            "forecast_accuracy_percentage": 0.9091,
        },
    ],

    "stock_optimization": [
        {
            "product_code": "JC-SH-001-M-BLU",
            "location_code": "DXB001",
            "optimization_run_date": "2026-07-04",
            "optimization_model_code": "BASIC_ROP",
            "avg_daily_sales": 1.2,
            "demand_std_dev": 0.5,
            "lead_time_days": 21,
            "service_level": 0.95,
            "safety_stock_qty": 5,
            "reorder_point_qty": 30,
            "recommended_order_qty": 25,
            "stock_cover_days": 5,
            "abc_class": "A",
            "xyz_class": "Y",
            "fsn_class": "F",
            "inventory_health_score": 42,
            "recommendation": "Reorder urgently / transfer from warehouse",
        },
        {
            "product_code": "OK-DR-010-4-PNK",
            "location_code": "SHJ001",
            "optimization_run_date": "2026-07-04",
            "optimization_model_code": "STOCK_HEALTH",
            "avg_daily_sales": 0.7,
            "demand_std_dev": 0.3,
            "lead_time_days": 18,
            "service_level": 0.95,
            "safety_stock_qty": 3,
            "reorder_point_qty": 16,
            "recommended_order_qty": 0,
            "stock_cover_days": 45,
            "abc_class": "B",
            "xyz_class": "Z",
            "fsn_class": "S",
            "inventory_health_score": 62,
            "recommendation": "Monitor overstock risk",
        },
        {
            "product_code": "PA-BG-020-STD-BGE",
            "location_code": "DXB001",
            "optimization_run_date": "2026-07-04",
            "optimization_model_code": "BASIC_ROP",
            "avg_daily_sales": 1.0,
            "demand_std_dev": 0.4,
            "lead_time_days": 35,
            "service_level": 0.95,
            "safety_stock_qty": 7,
            "reorder_point_qty": 42,
            "recommended_order_qty": 38,
            "stock_cover_days": 4,
            "abc_class": "A",
            "xyz_class": "Y",
            "fsn_class": "F",
            "inventory_health_score": 35,
            "recommendation": "Critical stockout risk - replenish now",
        },
    ],
}


def write_sample_file(file_type: str, rows: list[dict]) -> None:
    config = get_file_config(file_type)
    input_folder = config["input_folder"]

    input_folder.mkdir(parents=True, exist_ok=True)

    file_path = input_folder / f"{file_type}_sample.xlsx"

    df = pd.DataFrame(rows)
    df.to_excel(file_path, index=False)

    print(f"Created: {file_path}")
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")
    print("-" * 80)


def main() -> None:
    print("Generating sample Excel source files...")
    print("=" * 80)

    for file_type, rows in SAMPLE_DATA.items():
        write_sample_file(file_type, rows)

    print("Sample Excel source files generated successfully.")


if __name__ == "__main__":
    main()